 ## CLASS-EXERCISE 

1. Create a 2-d and 3-d numpy integer array 

In [9]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x)
print(y)



[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


2. Create a 2X2 integer array and show it's dimensions

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


3. Create a numpy array and  print the sum of third and fourth elements from the array 

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

5. Try example 4. using STEP method

6. Create a integer array and change data type from integer to boolean



7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

9. Create a numpy array of 5 person names and sort the values alpbabetically

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])