# Load in NumPy(remember to pip install numpy firts)

In [1]:
import numpy as np

Basic

In [4]:
#1D 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#Get Dimension
a.ndim

1

In [8]:
b.ndim

2

In [10]:
#Get Shape (row(3),column(0))
a.shape

(3,)

In [11]:
#(row(2),column(3))
b.shape

(2, 3)

In [23]:
#Get type
a = np.array([1,2,3],dtype='int16')
print(a)
a.dtype



[1 2 3]


dtype('int16')

In [24]:
#Get size ('int32'= 4, 'int16'= 2)
a.itemsize

2

In [25]:
#Get total size
a.nbytes

6

# Accessing/changing specific elemts,rows,columns,etc

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
a.shape

(2, 7)

In [32]:
#Get a specific element [row,column]

a[1,-6]

9

In [33]:
#Get a specific element [row,]
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
#Get a specific element [,column]
#[[ 1  2  3  4  5  6  7]
# [ 8  9 10 11 12 13 14]]
a[:,0]

array([1, 8])

# Getting a littlw more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]